create table CIM_EnabledLogicalElement (id number(19,0) not null, EnabledState number(10,0), OtherEnabledState varchar2(3000), RequestedState number(10,0), EnabledDefault number(10,0), TimeOfLastStateChange timestamp, primary key (id));
create table CIM_LogicalElement (id number(19,0) not null, primary key (id));
create table CIM_ManagedElement (id number(19,0) not null, discriminator_type varchar2(255 char) not null, Caption varchar2(3000), Description varchar2(3000), ElementName varchar2(3000), class_type varchar2(255 char), namespace_path varchar2(255 char), primary key (id));
create table CIM_ManagedSystemElement (id number(19,0) not null, InstallDate timestamp, Name varchar2(3000), OperationalStatus_value varchar2(4000 char), OperationalStatus_value_type number(10,0), StatusDescriptions_value varchar2(4000 char), StatusDescriptions_value_type number(10,0), primary key (id));
create table CIM_Service (id number(19,0) not null, SystemCreationClassName varchar2(3000), SystemName varchar2(3000), CreationClassName varchar2(3000), PrimaryOwnerName varchar2(3000), PrimaryOwnerContact varchar2(3000), Started number(1,0), primary key (id));
create table CIM_WBEMService (id number(19,0) not null, primary key (id));
create table HNSD_CiscoRouterProvider (id number(19,0) not null, primary key (id));
create table HNSD_GenericAgentProvider (id number(19,0) not null, CustomAgentVendor varchar2(3000), CustomAgentName varchar2(3000), DeviceClassName varchar2(3000), MonitoringInterfaceClass varchar2(3000), primary key (id));
create table HNSD_GenericProvider (id number(19,0) not null, DeviceDefaultVersion varchar2(3000), DeviceVersionOID varchar2(3000), DeviceSysObjectID varchar2(3000), primary key (id));
create table HNSD_Provider (id number(19,0) not null, AutoStart number(1,0), ServerId varchar2(3000), primary key (id));
create table UIM_AALGenericSNMPDeviceMonInt (id number(19,0) not null, LogFileMaxBackupIndex number(10,0), LogFileTrimMode number(10,0), primary key (id));
create table UIM_AutonomousDeviceInstantiat (id number(19,0) not null, Version varchar2(3000), LogFileEnabled number(1,0), LogLevel number(10,0), LogConsoleEnabled number(1,0), LogDirectory varchar2(3000), AutoStart number(1,0), primary key (id));
create table UIM_AutonomousNetworkResourceI (id number(19,0) not null, UniqueName varchar2(3000), primary key (id));
create table UIM_CiscoInterface (id number(19,0) not null, InDiscards varchar2(3000), InUnknownProtos varchar2(3000), Type varchar2(3000), LastChange varchar2(3000), OutOctets varchar2(3000), InOctets varchar2(3000), InUcastPkts varchar2(3000), InError varchar2(3000), OutUcastPkts varchar2(3000), OutDiscards varchar2(3000), OutErrors varchar2(3000), primary key (id));
create table UIM_CiscoRouterInstComponent (id number(19,0) not null, CustomAgentHome varchar2(3000), CustomAgentName varchar2(3000), CustomAgentVendor varchar2(3000), ElementType varchar2(3000), Script varchar2(3000), primary key (id));
create table UIM_CiscoRouterMgmtInterface (id number(19,0) not null, primary key (id));
create table UIM_CiscoRouterMonInterface (id number(19,0) not null, PerformancePollingTime number(10,0), PerformancePollingFrequency varchar2(3000), primary key (id));
create table UIM_CiscoRouterNetworkElement (id number(19,0) not null, Script varchar2(3000), SystemUpTimeTxt varchar2(3000), primary key (id));
create table UIM_GenericAgentMonInterface (id number(19,0) not null, AlertSeverityLevel number(10,0), AgentHome varchar2(3000), SystemName varchar2(3000), LogFileEnabled number(1,0), LogLevel number(10,0), LogConsoleEnabled number(1,0), LogDirectory varchar2(3000), primary key (id));
create table UIM_GenericDeviceInstComponent (id number(19,0) not null, StatusSleep number(19,0), AlertSeverityLevel number(10,0), primary key (id));
create table UIM_GenericDeviceMonInterface (id number(19,0) not null, StatusSleep number(19,0), CheckConnectionTimeStamp timestamp, primary key (id));
create table UIM_GenericInterface (id number(19,0) not null, PhysicalAddress varchar2(3000), AdminStatus number(10,0), OperStatus number(10,0), Index1 number(10,0), InterfaceType varchar2(3000), DuplexMode number(10,0), Speed number(19,0), HighSpeed number(19,0), Alias varchar2(3000), Mtu number(19,0), IfKeyName varchar2(3000), InterfaceNameIfMib varchar2(3000), InterfaceDescriptionIfMib varchar2(3000), primary key (id));
create table UIM_GenericNetworkElement (id number(19,0) not null, SystemUpTime number(19,0), SystemLocation varchar2(3000), SystemContact varchar2(3000), SnmpSleepTimeout number(10,0), DeviceName varchar2(3000), IsElementInEMS number(1,0), primary key (id));
create table UIM_GenericSNMPDeviceMonInterf (id number(19,0) not null, CustomAgentHome varchar2(3000), CustomAgentName varchar2(3000), CustomAgentVendor varchar2(3000), primary key (id));
create table UIM_InstantiationComponent (id number(19,0) not null, UIMClassName varchar2(3000), ManagedElementType varchar2(3000), Package varchar2(3000), Autonomous number(1,0), ProviderClassName varchar2(3000), primary key (id));
create table UIM_ManagedElement (id number(19,0) not null, discriminator_type varchar2(255 char) not null, Caption varchar2(3000), Description varchar2(3000), DisplayName varchar2(3000), DeletionAllowed number(1,0), MonitoringStatus number(5,0), class_type varchar2(255 char), namespace_path varchar2(255 char), primary key (id));
create table UIM_ManagedSystemElement (id number(19,0) not null, GeoCoordinates varchar2(3000), GeoInherited number(1,0), ElementType varchar2(3000), Name varchar2(3000), OperationalStatus_value varchar2(4000 char), OperationalStatus_value_type number(10,0), MaintenanceOutageAllowed number(1,0), SystemId number(19,0), primary key (id));
create table UIM_ManagementInterface (id number(19,0) not null, Name varchar2(3000), primary key (id));
create table UIM_MonitoringInterface (id number(19,0) not null, Name varchar2(3000), Status number(5,0), AutoStart number(1,0), IPAddress varchar2(3000), Version varchar2(3000), primary key (id));
create table UIM_NetworkElement (id number(19,0) not null, IPAddress varchar2(3000), ManagementStatus number(5,0), ManagedBy number(19,0), primary key (id));
create table UIM_NetworkResourceInstantiati (id number(19,0) not null, ManagementAgentName varchar2(3000), primary key (id));
create table UIM_PhysicalElement (id number(19,0) not null, primary key (id));
create table UIM_Port (id number(19,0) not null, TrafficType varchar2(3000), MediaType varchar2(3000), MaxOutboundLinks number(19,0), MaxInboundLinks number(19,0), OutboundConnections number(19,0), InboundConnections number(19,0), primary key (id));
create table UIM_SNMPDeviceInstComponent (id number(19,0) not null, AlarmSleep number(19,0), AttributeSleep number(19,0), ConfigurationSleep number(19,0), SnmpSleepTimeout number(10,0), SnmpWriteCommunity varchar2(3000), SnmpVersion number(10,0), SnmpTimeout number(19,0), SnmpRetries number(10,0), SnmpReadCommunity varchar2(3000), SnmpMaxSessions number(10,0), SnmpTrapPort varchar2(3000), SnmpDevicePort varchar2(3000), SnmpDeviceIP varchar2(3000), SnmpAuthPassPhrase varchar2(3000), SnmpAuthProtocol varchar2(3000), SnmpContextEngineID varchar2(3000), SnmpContextName varchar2(3000), SnmpPrivPassPhrase varchar2(3000), SnmpPrivProtocol varchar2(3000), SnmpSecurityLevel number(10,0), SnmpSecurityName varchar2(3000), SnmpMaxRepetitions number(10,0), SnmpNonRepeaters number(10,0), primary key (id));
create table UIM_SNMPDeviceMgmtInterface (id number(19,0) not null, primary key (id));
create table UIM_SNMPDeviceMonInterface (id number(19,0) not null, AlarmSleep number(19,0), AttributeSleep number(19,0), CheckConnectivityMethod number(10,0), ConfigurationSleep number(19,0), IcmpRetries number(10,0), IcmpTimeout number(19,0), SnmpWriteCommunity varchar2(3000), SnmpVersion number(10,0), SnmpTimeout number(19,0), SnmpRetries number(10,0), SnmpReadCommunity varchar2(3000), SnmpMaxSessions number(10,0), SnmpTrapPort varchar2(3000), SnmpDevicePort varchar2(3000), SnmpAuthPassPhrase varchar2(3000), SnmpAuthProtocol varchar2(3000), SnmpContextEngineID varchar2(3000), SnmpContextName varchar2(3000), SnmpPrivPassPhrase varchar2(3000), SnmpPrivProtocol varchar2(3000), SnmpSecurityLevel number(10,0), SnmpSecurityName varchar2(3000), SnmpMaxRepetitions number(10,0), SnmpNonRepeaters number(10,0), PollingCyclesNames_value varchar2(4000 char), PollingCyclesNames_value_type number(10,0), PollingCyclesIntervals_value varchar2(4000 char), PollingCyclesInterv_value_type number(10,0), primary key (id));
alter table CIM_EnabledLogicalElement add constraint FK816CE9C9F1286E5 foreign key (id) references CIM_ManagedElement;
alter table CIM_LogicalElement add constraint FKC048A16B18E71B18 foreign key (id) references CIM_ManagedElement;
create index index_1464451517305_owningName on CIM_ManagedElement (namespace_path);
alter table CIM_ManagedSystemElement add constraint FK95278526CB92C953 foreign key (id) references CIM_ManagedElement;
create index index_1464451517801_SystemName on CIM_Service (SystemName);
create index index_1464451517801_CreationCl on CIM_Service (CreationClassName);
create index index_1464451517801_SystemCrea on CIM_Service (SystemCreationClassName);
alter table CIM_Service add constraint FK9F6D72FDA87C33C6 foreign key (id) references CIM_ManagedElement;
alter table CIM_WBEMService add constraint FK285152EADE628CB3 foreign key (id) references CIM_ManagedElement;
alter table HNSD_CiscoRouterProvider add constraint FK37FD882B6E68CC58 foreign key (id) references CIM_ManagedElement;
alter table HNSD_GenericAgentProvider add constraint FK147BB507AB776D50 foreign key (id) references CIM_ManagedElement;
alter table HNSD_GenericProvider add constraint FKDA25166084DAB38D foreign key (id) references CIM_ManagedElement;
alter table HNSD_Provider add constraint FK6505D379653660C2 foreign key (id) references CIM_ManagedElement;
alter table UIM_AALGenericSNMPDeviceMonInt add constraint FK2C384968D2FC991F foreign key (id) references UIM_ManagedElement;
create index index_1548954695122_Version on UIM_AutonomousDeviceInstantiat (Version);
alter table UIM_AutonomousDeviceInstantiat add constraint FKC9E8D347C7D7B249 foreign key (id) references UIM_ManagedElement;
alter table UIM_AutonomousNetworkResourceI add constraint FK3C4ECAE33D3FB6BF foreign key (id) references UIM_ManagedElement;
alter table UIM_CiscoInterface add constraint FKF17400264A1279D3 foreign key (id) references UIM_ManagedElement;
alter table UIM_CiscoRouterInstComponent add constraint FK4A908B3B5B85F668 foreign key (id) references UIM_ManagedElement;
alter table UIM_CiscoRouterMgmtInterface add constraint FKC2CB3F5CD3C0AA89 foreign key (id) references UIM_ManagedElement;
alter table UIM_CiscoRouterMonInterface add constraint FK55DFC1291C9D65F2 foreign key (id) references UIM_ManagedElement;
alter table UIM_CiscoRouterNetworkElement add constraint FKD5FEE38AE3B554D3 foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericAgentMonInterface add constraint FK9C997B81AD8EE6AE foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericDeviceInstComponent add constraint FK5B846B3049A99DD foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericDeviceMonInterface add constraint FK3DA58E944B5BFFDD foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericInterface add constraint FK53F75C88FEACF9B5 foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericNetworkElement add constraint FKF70176FF8DFD2F48 foreign key (id) references UIM_ManagedElement;
alter table UIM_GenericSNMPDeviceMonInterf add constraint FKD0510F11CF566E1B foreign key (id) references UIM_ManagedElement;
create index index_1464451518210_UIMClassNa on UIM_InstantiationComponent (UIMClassName);
create index index_1464451518210_ManagedEle on UIM_InstantiationComponent (ManagedElementType);
alter table UIM_InstantiationComponent add constraint FK58EB6916A16530C3 foreign key (id) references UIM_ManagedElement;
create index index_1464451518187_owningName on UIM_ManagedElement (namespace_path);
create index index_1464451518196_Name on UIM_ManagedSystemElement (Name);
alter table UIM_ManagedSystemElement add constraint FK4D4390D483AED501 foreign key (id) references UIM_ManagedElement;
create index index_1464451518209_Name on UIM_ManagementInterface (Name);
alter table UIM_ManagementInterface add constraint FK520EF710F0B7A2D9 foreign key (id) references UIM_ManagedElement;
create index index_1464451518222_Name on UIM_MonitoringInterface (Name);
alter table UIM_MonitoringInterface add constraint FKE10180AB7FAA2C74 foreign key (id) references UIM_ManagedElement;
alter table UIM_NetworkElement add constraint FK71CA85D4CA68FF81 foreign key (id) references UIM_ManagedElement;
alter table UIM_NetworkResourceInstantiati add constraint FK2665D4D8D4D62A4F foreign key (id) references UIM_ManagedElement;
alter table UIM_PhysicalElement add constraint FKE20849FF9D377CC8 foreign key (id) references UIM_ManagedElement;
alter table UIM_Port add constraint FK1C30B8E7CB406114 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceInstComponent add constraint FKD568AE7D9C265346 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceMgmtInterface add constraint FK4DA3629E14610767 foreign key (id) references UIM_ManagedElement;
alter table UIM_SNMPDeviceMonInterface add constraint FKC5B52DA7E2EF554 foreign key (id) references UIM_ManagedElement;
create sequence total_instance_sequence;
